### ISSUE TITLE
Fishtank is White w/ Optifine

### ISSUE THREAD

**Issue by WenXin20** [MrCrayfish/MrCrayfishFurnitureMod-CE#3]
Instead of clear glass, it shows up as a white cube.

**Comment by MrCrayfish** [comment]
I'll look into it. My guess is that Optifine seems to change the rendering property for textures. For the fishtank, I am using a property called CUTOUT. It means it only renders full opacity pixels. Semi or no opacity don't get rendered. Optifine doesn't see it as that and instead makes all the pixels full opactiy (even if they were semi transparent) and that's why you see a white cube. This is not an easy fix.

**Comment by WenXin20** [comment]
Ok, thanks for looking into it.

**Comment by MrCrayfish** [comment]
Fixed. Changed texture to normal glass.

**Comment by WenXin20** [comment]
Thanks
